server:                       # 服务端配置
  name: my_app                # 业务进程名
  filter:                     # 过滤器列表
    - logger
    - recover
    - auth
    - trace
  service:                    # 对外提供的服务列表
    - name: login
      port: 8899
      network: tcp
      protocol: minirpc
      timeout: 3000
    - name: user
      port: 8900
      network: udp
      protocol: http
      timeout: 1000


client:
  filter:
    - logger
    - metric
  timeout: 1000                 # 全局的超时时间配置
  service:                      # 依赖的下游服务列表（rpc/mysql/redis）
    - name: activity
      endpoint: dsn://xxx
      protocol: http
      timeout: 400              # 针对该服务的超时时间配置
      api:
        - name: get_info
          timeut: 800           # 针对接口级别的超时时间配置


component:                              # 组件配置
  logger:                               # 日志组件配置
    level: info                       # 日志级别
    path: /logs/my_app/server.log     # 日志输出目录
    roll_type: size                   # 日志滚动方式
    max_size: 500                     # 日志最大大小
    compress: false                   # 是否压缩
  tracing:
    level: info